# Generated by Django 4.1.7 on 2023-03-30 18:39

from django.db import migrations

def populate_db(apps, schema_editor):
    units = {'t_oz': 14.583, 'T': .0005, 'g': 453.592, 'kg': .453592, 'lb': 1, 'oz': 16}
    Unit = apps.get_model('unitconv', 'Unit')
    for unit in units:
        Unit(name=unit, conversion=units[unit]).save()

class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
